// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStoreConf.proto

package dimit.store.conf;

public interface ChannelConfOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelConf)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 v = 1;</code>
   */
  int getV();

  /**
   * <pre>
   * channel id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * channel id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * name, unique
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * name, unique
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.ChannelStatus status = 4;</code>
   */
  int getStatusValue();
  /**
   * <code>.ChannelStatus status = 4;</code>
   */
  dimit.store.conf.ChannelStatus getStatus();

  /**
   * <pre>
   * group id
   * </pre>
   *
   * <code>string gid = 5;</code>
   */
  java.lang.String getGid();
  /**
   * <pre>
   * group id
   * </pre>
   *
   * <code>string gid = 5;</code>
   */
  com.google.protobuf.ByteString
      getGidBytes();

  /**
   * <pre>
   * max-tps of the channel
   * </pre>
   *
   * <code>float tps = 6;</code>
   */
  float getTps();

  /**
   * <pre>
   * channel priority [1-9]. The maximum-Priority is 9. Default is 5
   * </pre>
   *
   * <code>int32 priority = 7;</code>
   */
  int getPriority();

  /**
   * <code>repeated string tag = 8;</code>
   */
  java.util.List<java.lang.String>
      getTagList();
  /**
   * <code>repeated string tag = 8;</code>
   */
  int getTagCount();
  /**
   * <code>repeated string tag = 8;</code>
   */
  java.lang.String getTag(int index);
  /**
   * <code>repeated string tag = 8;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes(int index);

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  long getCt();

  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  long getMt();
}
