// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStoreConf.proto

package dimit.store.conf;

/**
 * <pre>
 * </pre>
 *
 * Protobuf type {@code ChannelConf}
 */
public  final class ChannelConf extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChannelConf)
    ChannelConfOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelConf.newBuilder() to construct.
  private ChannelConf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelConf() {
    v_ = 0;
    id_ = "";
    name_ = "";
    status_ = 0;
    gid_ = "";
    tps_ = 0F;
    priority_ = 0;
    tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    ct_ = 0L;
    mt_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelConf(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            v_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            gid_ = s;
            break;
          }
          case 53: {

            tps_ = input.readFloat();
            break;
          }
          case 56: {

            priority_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              tag_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            tag_.add(s);
            break;
          }
          case 72: {

            ct_ = input.readUInt64();
            break;
          }
          case 80: {

            mt_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        tag_ = tag_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dimit.store.conf.DimitStoreConf.internal_static_ChannelConf_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dimit.store.conf.DimitStoreConf.internal_static_ChannelConf_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dimit.store.conf.ChannelConf.class, dimit.store.conf.ChannelConf.Builder.class);
  }

  private int bitField0_;
  public static final int V_FIELD_NUMBER = 1;
  private int v_;
  /**
   * <code>uint32 v = 1;</code>
   */
  public int getV() {
    return v_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * channel id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * channel id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * name, unique
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name, unique
   * </pre>
   *
   * <code>string name = 3;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>.ChannelStatus status = 4;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.ChannelStatus status = 4;</code>
   */
  public dimit.store.conf.ChannelStatus getStatus() {
    dimit.store.conf.ChannelStatus result = dimit.store.conf.ChannelStatus.valueOf(status_);
    return result == null ? dimit.store.conf.ChannelStatus.UNRECOGNIZED : result;
  }

  public static final int GID_FIELD_NUMBER = 5;
  private volatile java.lang.Object gid_;
  /**
   * <pre>
   * group id
   * </pre>
   *
   * <code>string gid = 5;</code>
   */
  public java.lang.String getGid() {
    java.lang.Object ref = gid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      gid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * group id
   * </pre>
   *
   * <code>string gid = 5;</code>
   */
  public com.google.protobuf.ByteString
      getGidBytes() {
    java.lang.Object ref = gid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      gid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TPS_FIELD_NUMBER = 6;
  private float tps_;
  /**
   * <pre>
   * max-tps of the channel
   * </pre>
   *
   * <code>float tps = 6;</code>
   */
  public float getTps() {
    return tps_;
  }

  public static final int PRIORITY_FIELD_NUMBER = 7;
  private int priority_;
  /**
   * <pre>
   * channel priority [1-9]. The maximum-Priority is 9. Default is 5
   * </pre>
   *
   * <code>int32 priority = 7;</code>
   */
  public int getPriority() {
    return priority_;
  }

  public static final int TAG_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList tag_;
  /**
   * <code>repeated string tag = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getTagList() {
    return tag_;
  }
  /**
   * <code>repeated string tag = 8;</code>
   */
  public int getTagCount() {
    return tag_.size();
  }
  /**
   * <code>repeated string tag = 8;</code>
   */
  public java.lang.String getTag(int index) {
    return tag_.get(index);
  }
  /**
   * <code>repeated string tag = 8;</code>
   */
  public com.google.protobuf.ByteString
      getTagBytes(int index) {
    return tag_.getByteString(index);
  }

  public static final int CT_FIELD_NUMBER = 9;
  private long ct_;
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  public long getCt() {
    return ct_;
  }

  public static final int MT_FIELD_NUMBER = 10;
  private long mt_;
  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  public long getMt() {
    return mt_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (v_ != 0) {
      output.writeUInt32(1, v_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (status_ != dimit.store.conf.ChannelStatus.CLOSED.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (!getGidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, gid_);
    }
    if (tps_ != 0F) {
      output.writeFloat(6, tps_);
    }
    if (priority_ != 0) {
      output.writeInt32(7, priority_);
    }
    for (int i = 0; i < tag_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tag_.getRaw(i));
    }
    if (ct_ != 0L) {
      output.writeUInt64(9, ct_);
    }
    if (mt_ != 0L) {
      output.writeUInt64(10, mt_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (v_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, v_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (status_ != dimit.store.conf.ChannelStatus.CLOSED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (!getGidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, gid_);
    }
    if (tps_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(6, tps_);
    }
    if (priority_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, priority_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < tag_.size(); i++) {
        dataSize += computeStringSizeNoTag(tag_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTagList().size();
    }
    if (ct_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, ct_);
    }
    if (mt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, mt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dimit.store.conf.ChannelConf)) {
      return super.equals(obj);
    }
    dimit.store.conf.ChannelConf other = (dimit.store.conf.ChannelConf) obj;

    boolean result = true;
    result = result && (getV()
        == other.getV());
    result = result && getId()
        .equals(other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && status_ == other.status_;
    result = result && getGid()
        .equals(other.getGid());
    result = result && (
        java.lang.Float.floatToIntBits(getTps())
        == java.lang.Float.floatToIntBits(
            other.getTps()));
    result = result && (getPriority()
        == other.getPriority());
    result = result && getTagList()
        .equals(other.getTagList());
    result = result && (getCt()
        == other.getCt());
    result = result && (getMt()
        == other.getMt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + V_FIELD_NUMBER;
    hash = (53 * hash) + getV();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + GID_FIELD_NUMBER;
    hash = (53 * hash) + getGid().hashCode();
    hash = (37 * hash) + TPS_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTps());
    hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
    hash = (53 * hash) + getPriority();
    if (getTagCount() > 0) {
      hash = (37 * hash) + TAG_FIELD_NUMBER;
      hash = (53 * hash) + getTagList().hashCode();
    }
    hash = (37 * hash) + CT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCt());
    hash = (37 * hash) + MT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dimit.store.conf.ChannelConf parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.conf.ChannelConf parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.conf.ChannelConf parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dimit.store.conf.ChannelConf parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dimit.store.conf.ChannelConf parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dimit.store.conf.ChannelConf parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dimit.store.conf.ChannelConf prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * </pre>
   *
   * Protobuf type {@code ChannelConf}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChannelConf)
      dimit.store.conf.ChannelConfOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dimit.store.conf.DimitStoreConf.internal_static_ChannelConf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dimit.store.conf.DimitStoreConf.internal_static_ChannelConf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dimit.store.conf.ChannelConf.class, dimit.store.conf.ChannelConf.Builder.class);
    }

    // Construct using dimit.store.conf.ChannelConf.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      v_ = 0;

      id_ = "";

      name_ = "";

      status_ = 0;

      gid_ = "";

      tps_ = 0F;

      priority_ = 0;

      tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      ct_ = 0L;

      mt_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dimit.store.conf.DimitStoreConf.internal_static_ChannelConf_descriptor;
    }

    public dimit.store.conf.ChannelConf getDefaultInstanceForType() {
      return dimit.store.conf.ChannelConf.getDefaultInstance();
    }

    public dimit.store.conf.ChannelConf build() {
      dimit.store.conf.ChannelConf result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public dimit.store.conf.ChannelConf buildPartial() {
      dimit.store.conf.ChannelConf result = new dimit.store.conf.ChannelConf(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.v_ = v_;
      result.id_ = id_;
      result.name_ = name_;
      result.status_ = status_;
      result.gid_ = gid_;
      result.tps_ = tps_;
      result.priority_ = priority_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        tag_ = tag_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.tag_ = tag_;
      result.ct_ = ct_;
      result.mt_ = mt_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dimit.store.conf.ChannelConf) {
        return mergeFrom((dimit.store.conf.ChannelConf)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dimit.store.conf.ChannelConf other) {
      if (other == dimit.store.conf.ChannelConf.getDefaultInstance()) return this;
      if (other.getV() != 0) {
        setV(other.getV());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (!other.getGid().isEmpty()) {
        gid_ = other.gid_;
        onChanged();
      }
      if (other.getTps() != 0F) {
        setTps(other.getTps());
      }
      if (other.getPriority() != 0) {
        setPriority(other.getPriority());
      }
      if (!other.tag_.isEmpty()) {
        if (tag_.isEmpty()) {
          tag_ = other.tag_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureTagIsMutable();
          tag_.addAll(other.tag_);
        }
        onChanged();
      }
      if (other.getCt() != 0L) {
        setCt(other.getCt());
      }
      if (other.getMt() != 0L) {
        setMt(other.getMt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dimit.store.conf.ChannelConf parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dimit.store.conf.ChannelConf) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int v_ ;
    /**
     * <code>uint32 v = 1;</code>
     */
    public int getV() {
      return v_;
    }
    /**
     * <code>uint32 v = 1;</code>
     */
    public Builder setV(int value) {
      
      v_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 v = 1;</code>
     */
    public Builder clearV() {
      
      v_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * channel id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * channel id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * channel id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * channel id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * channel id
     * </pre>
     *
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * name, unique
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name, unique
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name, unique
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name, unique
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name, unique
     * </pre>
     *
     * <code>string name = 3;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.ChannelStatus status = 4;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ChannelStatus status = 4;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ChannelStatus status = 4;</code>
     */
    public dimit.store.conf.ChannelStatus getStatus() {
      dimit.store.conf.ChannelStatus result = dimit.store.conf.ChannelStatus.valueOf(status_);
      return result == null ? dimit.store.conf.ChannelStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.ChannelStatus status = 4;</code>
     */
    public Builder setStatus(dimit.store.conf.ChannelStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ChannelStatus status = 4;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object gid_ = "";
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>string gid = 5;</code>
     */
    public java.lang.String getGid() {
      java.lang.Object ref = gid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>string gid = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGidBytes() {
      java.lang.Object ref = gid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>string gid = 5;</code>
     */
    public Builder setGid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      gid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>string gid = 5;</code>
     */
    public Builder clearGid() {
      
      gid_ = getDefaultInstance().getGid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * group id
     * </pre>
     *
     * <code>string gid = 5;</code>
     */
    public Builder setGidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      gid_ = value;
      onChanged();
      return this;
    }

    private float tps_ ;
    /**
     * <pre>
     * max-tps of the channel
     * </pre>
     *
     * <code>float tps = 6;</code>
     */
    public float getTps() {
      return tps_;
    }
    /**
     * <pre>
     * max-tps of the channel
     * </pre>
     *
     * <code>float tps = 6;</code>
     */
    public Builder setTps(float value) {
      
      tps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * max-tps of the channel
     * </pre>
     *
     * <code>float tps = 6;</code>
     */
    public Builder clearTps() {
      
      tps_ = 0F;
      onChanged();
      return this;
    }

    private int priority_ ;
    /**
     * <pre>
     * channel priority [1-9]. The maximum-Priority is 9. Default is 5
     * </pre>
     *
     * <code>int32 priority = 7;</code>
     */
    public int getPriority() {
      return priority_;
    }
    /**
     * <pre>
     * channel priority [1-9]. The maximum-Priority is 9. Default is 5
     * </pre>
     *
     * <code>int32 priority = 7;</code>
     */
    public Builder setPriority(int value) {
      
      priority_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * channel priority [1-9]. The maximum-Priority is 9. Default is 5
     * </pre>
     *
     * <code>int32 priority = 7;</code>
     */
    public Builder clearPriority() {
      
      priority_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureTagIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        tag_ = new com.google.protobuf.LazyStringArrayList(tag_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTagList() {
      return tag_.getUnmodifiableView();
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public int getTagCount() {
      return tag_.size();
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public java.lang.String getTag(int index) {
      return tag_.get(index);
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTagBytes(int index) {
      return tag_.getByteString(index);
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public Builder setTag(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
      tag_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public Builder addTag(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureTagIsMutable();
      tag_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public Builder addAllTag(
        java.lang.Iterable<java.lang.String> values) {
      ensureTagIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, tag_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public Builder clearTag() {
      tag_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string tag = 8;</code>
     */
    public Builder addTagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureTagIsMutable();
      tag_.add(value);
      onChanged();
      return this;
    }

    private long ct_ ;
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public long getCt() {
      return ct_;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public Builder setCt(long value) {
      
      ct_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public Builder clearCt() {
      
      ct_ = 0L;
      onChanged();
      return this;
    }

    private long mt_ ;
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public long getMt() {
      return mt_;
    }
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public Builder setMt(long value) {
      
      mt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public Builder clearMt() {
      
      mt_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChannelConf)
  }

  // @@protoc_insertion_point(class_scope:ChannelConf)
  private static final dimit.store.conf.ChannelConf DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dimit.store.conf.ChannelConf();
  }

  public static dimit.store.conf.ChannelConf getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelConf>
      PARSER = new com.google.protobuf.AbstractParser<ChannelConf>() {
    public ChannelConf parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelConf(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelConf> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelConf> getParserForType() {
    return PARSER;
  }

  public dimit.store.conf.ChannelConf getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

