// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStoreConf.proto

package dimit.store.conf;

/**
 * Protobuf enum {@code ChannelStatus}
 */
public enum ChannelStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CLOSED = 0;</code>
   */
  CLOSED(0),
  /**
   * <code>PRIMARY = 1;</code>
   */
  PRIMARY(1),
  /**
   * <code>STANDBY = 2;</code>
   */
  STANDBY(2),
  /**
   * <code>INVALID = 3;</code>
   */
  INVALID(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CLOSED = 0;</code>
   */
  public static final int CLOSED_VALUE = 0;
  /**
   * <code>PRIMARY = 1;</code>
   */
  public static final int PRIMARY_VALUE = 1;
  /**
   * <code>STANDBY = 2;</code>
   */
  public static final int STANDBY_VALUE = 2;
  /**
   * <code>INVALID = 3;</code>
   */
  public static final int INVALID_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ChannelStatus valueOf(int value) {
    return forNumber(value);
  }

  public static ChannelStatus forNumber(int value) {
    switch (value) {
      case 0: return CLOSED;
      case 1: return PRIMARY;
      case 2: return STANDBY;
      case 3: return INVALID;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ChannelStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ChannelStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ChannelStatus>() {
          public ChannelStatus findValueByNumber(int number) {
            return ChannelStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dimit.store.conf.DimitStoreConf.getDescriptor().getEnumTypes().get(1);
  }

  private static final ChannelStatus[] VALUES = values();

  public static ChannelStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ChannelStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ChannelStatus)
}

