// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStoreConf.proto

package dimit.store.conf;

/**
 * <pre>
 *range:[0,255]
 * </pre>
 *
 * Protobuf enum {@code MagicFlag}
 */
public enum MagicFlag
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * conf
   * </pre>
   *
   * <code>DIMIT_CONF = 0;</code>
   */
  DIMIT_CONF(0),
  /**
   * <code>CHANNEL_GROUP_CONF = 1;</code>
   */
  CHANNEL_GROUP_CONF(1),
  /**
   * <code>CHANNEL_CONF = 2;</code>
   */
  CHANNEL_CONF(2),
  /**
   * <pre>
   * store
   * </pre>
   *
   * <code>DIMIT = 3;</code>
   */
  DIMIT(3),
  /**
   * <code>CHANNEL_GROUP = 4;</code>
   */
  CHANNEL_GROUP(4),
  /**
   * <code>CHANNEL = 5;</code>
   */
  CHANNEL(5),
  /**
   * <pre>
   * stat
   * </pre>
   *
   * <code>CHANNEL_STAT = 6;</code>
   */
  CHANNEL_STAT(6),
  /**
   * <code>CHANNEL_TOTAL_STAT = 7;</code>
   */
  CHANNEL_TOTAL_STAT(7),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * conf
   * </pre>
   *
   * <code>DIMIT_CONF = 0;</code>
   */
  public static final int DIMIT_CONF_VALUE = 0;
  /**
   * <code>CHANNEL_GROUP_CONF = 1;</code>
   */
  public static final int CHANNEL_GROUP_CONF_VALUE = 1;
  /**
   * <code>CHANNEL_CONF = 2;</code>
   */
  public static final int CHANNEL_CONF_VALUE = 2;
  /**
   * <pre>
   * store
   * </pre>
   *
   * <code>DIMIT = 3;</code>
   */
  public static final int DIMIT_VALUE = 3;
  /**
   * <code>CHANNEL_GROUP = 4;</code>
   */
  public static final int CHANNEL_GROUP_VALUE = 4;
  /**
   * <code>CHANNEL = 5;</code>
   */
  public static final int CHANNEL_VALUE = 5;
  /**
   * <pre>
   * stat
   * </pre>
   *
   * <code>CHANNEL_STAT = 6;</code>
   */
  public static final int CHANNEL_STAT_VALUE = 6;
  /**
   * <code>CHANNEL_TOTAL_STAT = 7;</code>
   */
  public static final int CHANNEL_TOTAL_STAT_VALUE = 7;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MagicFlag valueOf(int value) {
    return forNumber(value);
  }

  public static MagicFlag forNumber(int value) {
    switch (value) {
      case 0: return DIMIT_CONF;
      case 1: return CHANNEL_GROUP_CONF;
      case 2: return CHANNEL_CONF;
      case 3: return DIMIT;
      case 4: return CHANNEL_GROUP;
      case 5: return CHANNEL;
      case 6: return CHANNEL_STAT;
      case 7: return CHANNEL_TOTAL_STAT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MagicFlag>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MagicFlag> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MagicFlag>() {
          public MagicFlag findValueByNumber(int number) {
            return MagicFlag.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dimit.store.conf.DimitStoreConf.getDescriptor().getEnumTypes().get(0);
  }

  private static final MagicFlag[] VALUES = values();

  public static MagicFlag valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MagicFlag(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MagicFlag)
}

