// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStore.proto

package dimit.store;

public interface ChannelSendStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelSendStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 v = 1;</code>
   */
  int getV();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string channelId = 3;</code>
   */
  java.lang.String getChannelId();
  /**
   * <code>string channelId = 3;</code>
   */
  com.google.protobuf.ByteString
      getChannelIdBytes();

  /**
   * <code>uint64 succCount = 4;</code>
   */
  long getSuccCount();

  /**
   * <pre>
   * millisecond
   * </pre>
   *
   * <code>uint64 succTime = 5;</code>
   */
  long getSuccTime();

  /**
   * <code>uint64 failCount = 6;</code>
   */
  long getFailCount();

  /**
   * <code>uint64 failTime = 7;</code>
   */
  long getFailTime();

  /**
   * <code>double tps = 8;</code>
   */
  double getTps();

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  long getCt();

  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  long getMt();
}
