// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStore.proto

package dimit.store;

/**
 * Protobuf type {@code ChannelTotalStat}
 */
public  final class ChannelTotalStat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ChannelTotalStat)
    ChannelTotalStatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelTotalStat.newBuilder() to construct.
  private ChannelTotalStat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelTotalStat() {
    v_ = 0;
    id_ = "";
    cid_ = "";
    count_ = 0L;
    time_ = 0L;
    succCount_ = 0L;
    succTime_ = 0L;
    tps_ = 0D;
    avgTime_ = 0D;
    succRate_ = 0D;
    ct_ = 0L;
    mt_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelTotalStat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            v_ = input.readUInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            cid_ = s;
            break;
          }
          case 32: {

            count_ = input.readUInt64();
            break;
          }
          case 40: {

            time_ = input.readUInt64();
            break;
          }
          case 48: {

            succCount_ = input.readUInt64();
            break;
          }
          case 56: {

            succTime_ = input.readUInt64();
            break;
          }
          case 65: {

            tps_ = input.readDouble();
            break;
          }
          case 72: {

            ct_ = input.readUInt64();
            break;
          }
          case 80: {

            mt_ = input.readUInt64();
            break;
          }
          case 89: {

            avgTime_ = input.readDouble();
            break;
          }
          case 97: {

            succRate_ = input.readDouble();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dimit.store.DimitStore.internal_static_ChannelTotalStat_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dimit.store.DimitStore.internal_static_ChannelTotalStat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dimit.store.ChannelTotalStat.class, dimit.store.ChannelTotalStat.Builder.class);
  }

  public static final int V_FIELD_NUMBER = 1;
  private int v_;
  /**
   * <code>uint32 v = 1;</code>
   */
  public int getV() {
    return v_;
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CID_FIELD_NUMBER = 3;
  private volatile java.lang.Object cid_;
  /**
   * <pre>
   * ChannelConf's id
   * </pre>
   *
   * <code>string cid = 3;</code>
   */
  public java.lang.String getCid() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ChannelConf's id
   * </pre>
   *
   * <code>string cid = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCidBytes() {
    java.lang.Object ref = cid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COUNT_FIELD_NUMBER = 4;
  private long count_;
  /**
   * <pre>
   * accumulative
   * </pre>
   *
   * <code>uint64 count = 4;</code>
   */
  public long getCount() {
    return count_;
  }

  public static final int TIME_FIELD_NUMBER = 5;
  private long time_;
  /**
   * <pre>
   * total send millisecond
   * </pre>
   *
   * <code>uint64 time = 5;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int SUCCCOUNT_FIELD_NUMBER = 6;
  private long succCount_;
  /**
   * <code>uint64 succCount = 6;</code>
   */
  public long getSuccCount() {
    return succCount_;
  }

  public static final int SUCCTIME_FIELD_NUMBER = 7;
  private long succTime_;
  /**
   * <code>uint64 succTime = 7;</code>
   */
  public long getSuccTime() {
    return succTime_;
  }

  public static final int TPS_FIELD_NUMBER = 8;
  private double tps_;
  /**
   * <pre>
   * interval mean
   * </pre>
   *
   * <code>double tps = 8;</code>
   */
  public double getTps() {
    return tps_;
  }

  public static final int AVGTIME_FIELD_NUMBER = 11;
  private double avgTime_;
  /**
   * <pre>
   * average calling millisecond
   * </pre>
   *
   * <code>double avgTime = 11;</code>
   */
  public double getAvgTime() {
    return avgTime_;
  }

  public static final int SUCCRATE_FIELD_NUMBER = 12;
  private double succRate_;
  /**
   * <code>double succRate = 12;</code>
   */
  public double getSuccRate() {
    return succRate_;
  }

  public static final int CT_FIELD_NUMBER = 9;
  private long ct_;
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  public long getCt() {
    return ct_;
  }

  public static final int MT_FIELD_NUMBER = 10;
  private long mt_;
  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  public long getMt() {
    return mt_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (v_ != 0) {
      output.writeUInt32(1, v_);
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (!getCidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cid_);
    }
    if (count_ != 0L) {
      output.writeUInt64(4, count_);
    }
    if (time_ != 0L) {
      output.writeUInt64(5, time_);
    }
    if (succCount_ != 0L) {
      output.writeUInt64(6, succCount_);
    }
    if (succTime_ != 0L) {
      output.writeUInt64(7, succTime_);
    }
    if (tps_ != 0D) {
      output.writeDouble(8, tps_);
    }
    if (ct_ != 0L) {
      output.writeUInt64(9, ct_);
    }
    if (mt_ != 0L) {
      output.writeUInt64(10, mt_);
    }
    if (avgTime_ != 0D) {
      output.writeDouble(11, avgTime_);
    }
    if (succRate_ != 0D) {
      output.writeDouble(12, succRate_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (v_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, v_);
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (!getCidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cid_);
    }
    if (count_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, count_);
    }
    if (time_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, time_);
    }
    if (succCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(6, succCount_);
    }
    if (succTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, succTime_);
    }
    if (tps_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, tps_);
    }
    if (ct_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, ct_);
    }
    if (mt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(10, mt_);
    }
    if (avgTime_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, avgTime_);
    }
    if (succRate_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(12, succRate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dimit.store.ChannelTotalStat)) {
      return super.equals(obj);
    }
    dimit.store.ChannelTotalStat other = (dimit.store.ChannelTotalStat) obj;

    boolean result = true;
    result = result && (getV()
        == other.getV());
    result = result && getId()
        .equals(other.getId());
    result = result && getCid()
        .equals(other.getCid());
    result = result && (getCount()
        == other.getCount());
    result = result && (getTime()
        == other.getTime());
    result = result && (getSuccCount()
        == other.getSuccCount());
    result = result && (getSuccTime()
        == other.getSuccTime());
    result = result && (
        java.lang.Double.doubleToLongBits(getTps())
        == java.lang.Double.doubleToLongBits(
            other.getTps()));
    result = result && (
        java.lang.Double.doubleToLongBits(getAvgTime())
        == java.lang.Double.doubleToLongBits(
            other.getAvgTime()));
    result = result && (
        java.lang.Double.doubleToLongBits(getSuccRate())
        == java.lang.Double.doubleToLongBits(
            other.getSuccRate()));
    result = result && (getCt()
        == other.getCt());
    result = result && (getMt()
        == other.getMt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + V_FIELD_NUMBER;
    hash = (53 * hash) + getV();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CID_FIELD_NUMBER;
    hash = (53 * hash) + getCid().hashCode();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCount());
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTime());
    hash = (37 * hash) + SUCCCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSuccCount());
    hash = (37 * hash) + SUCCTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSuccTime());
    hash = (37 * hash) + TPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTps()));
    hash = (37 * hash) + AVGTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvgTime()));
    hash = (37 * hash) + SUCCRATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getSuccRate()));
    hash = (37 * hash) + CT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCt());
    hash = (37 * hash) + MT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dimit.store.ChannelTotalStat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.ChannelTotalStat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dimit.store.ChannelTotalStat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dimit.store.ChannelTotalStat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dimit.store.ChannelTotalStat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dimit.store.ChannelTotalStat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dimit.store.ChannelTotalStat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ChannelTotalStat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ChannelTotalStat)
      dimit.store.ChannelTotalStatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dimit.store.DimitStore.internal_static_ChannelTotalStat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dimit.store.DimitStore.internal_static_ChannelTotalStat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dimit.store.ChannelTotalStat.class, dimit.store.ChannelTotalStat.Builder.class);
    }

    // Construct using dimit.store.ChannelTotalStat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      v_ = 0;

      id_ = "";

      cid_ = "";

      count_ = 0L;

      time_ = 0L;

      succCount_ = 0L;

      succTime_ = 0L;

      tps_ = 0D;

      avgTime_ = 0D;

      succRate_ = 0D;

      ct_ = 0L;

      mt_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dimit.store.DimitStore.internal_static_ChannelTotalStat_descriptor;
    }

    public dimit.store.ChannelTotalStat getDefaultInstanceForType() {
      return dimit.store.ChannelTotalStat.getDefaultInstance();
    }

    public dimit.store.ChannelTotalStat build() {
      dimit.store.ChannelTotalStat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public dimit.store.ChannelTotalStat buildPartial() {
      dimit.store.ChannelTotalStat result = new dimit.store.ChannelTotalStat(this);
      result.v_ = v_;
      result.id_ = id_;
      result.cid_ = cid_;
      result.count_ = count_;
      result.time_ = time_;
      result.succCount_ = succCount_;
      result.succTime_ = succTime_;
      result.tps_ = tps_;
      result.avgTime_ = avgTime_;
      result.succRate_ = succRate_;
      result.ct_ = ct_;
      result.mt_ = mt_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dimit.store.ChannelTotalStat) {
        return mergeFrom((dimit.store.ChannelTotalStat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dimit.store.ChannelTotalStat other) {
      if (other == dimit.store.ChannelTotalStat.getDefaultInstance()) return this;
      if (other.getV() != 0) {
        setV(other.getV());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getCid().isEmpty()) {
        cid_ = other.cid_;
        onChanged();
      }
      if (other.getCount() != 0L) {
        setCount(other.getCount());
      }
      if (other.getTime() != 0L) {
        setTime(other.getTime());
      }
      if (other.getSuccCount() != 0L) {
        setSuccCount(other.getSuccCount());
      }
      if (other.getSuccTime() != 0L) {
        setSuccTime(other.getSuccTime());
      }
      if (other.getTps() != 0D) {
        setTps(other.getTps());
      }
      if (other.getAvgTime() != 0D) {
        setAvgTime(other.getAvgTime());
      }
      if (other.getSuccRate() != 0D) {
        setSuccRate(other.getSuccRate());
      }
      if (other.getCt() != 0L) {
        setCt(other.getCt());
      }
      if (other.getMt() != 0L) {
        setMt(other.getMt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dimit.store.ChannelTotalStat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dimit.store.ChannelTotalStat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int v_ ;
    /**
     * <code>uint32 v = 1;</code>
     */
    public int getV() {
      return v_;
    }
    /**
     * <code>uint32 v = 1;</code>
     */
    public Builder setV(int value) {
      
      v_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 v = 1;</code>
     */
    public Builder clearV() {
      
      v_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cid_ = "";
    /**
     * <pre>
     * ChannelConf's id
     * </pre>
     *
     * <code>string cid = 3;</code>
     */
    public java.lang.String getCid() {
      java.lang.Object ref = cid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ChannelConf's id
     * </pre>
     *
     * <code>string cid = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCidBytes() {
      java.lang.Object ref = cid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ChannelConf's id
     * </pre>
     *
     * <code>string cid = 3;</code>
     */
    public Builder setCid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ChannelConf's id
     * </pre>
     *
     * <code>string cid = 3;</code>
     */
    public Builder clearCid() {
      
      cid_ = getDefaultInstance().getCid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ChannelConf's id
     * </pre>
     *
     * <code>string cid = 3;</code>
     */
    public Builder setCidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cid_ = value;
      onChanged();
      return this;
    }

    private long count_ ;
    /**
     * <pre>
     * accumulative
     * </pre>
     *
     * <code>uint64 count = 4;</code>
     */
    public long getCount() {
      return count_;
    }
    /**
     * <pre>
     * accumulative
     * </pre>
     *
     * <code>uint64 count = 4;</code>
     */
    public Builder setCount(long value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * accumulative
     * </pre>
     *
     * <code>uint64 count = 4;</code>
     */
    public Builder clearCount() {
      
      count_ = 0L;
      onChanged();
      return this;
    }

    private long time_ ;
    /**
     * <pre>
     * total send millisecond
     * </pre>
     *
     * <code>uint64 time = 5;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <pre>
     * total send millisecond
     * </pre>
     *
     * <code>uint64 time = 5;</code>
     */
    public Builder setTime(long value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * total send millisecond
     * </pre>
     *
     * <code>uint64 time = 5;</code>
     */
    public Builder clearTime() {
      
      time_ = 0L;
      onChanged();
      return this;
    }

    private long succCount_ ;
    /**
     * <code>uint64 succCount = 6;</code>
     */
    public long getSuccCount() {
      return succCount_;
    }
    /**
     * <code>uint64 succCount = 6;</code>
     */
    public Builder setSuccCount(long value) {
      
      succCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 succCount = 6;</code>
     */
    public Builder clearSuccCount() {
      
      succCount_ = 0L;
      onChanged();
      return this;
    }

    private long succTime_ ;
    /**
     * <code>uint64 succTime = 7;</code>
     */
    public long getSuccTime() {
      return succTime_;
    }
    /**
     * <code>uint64 succTime = 7;</code>
     */
    public Builder setSuccTime(long value) {
      
      succTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 succTime = 7;</code>
     */
    public Builder clearSuccTime() {
      
      succTime_ = 0L;
      onChanged();
      return this;
    }

    private double tps_ ;
    /**
     * <pre>
     * interval mean
     * </pre>
     *
     * <code>double tps = 8;</code>
     */
    public double getTps() {
      return tps_;
    }
    /**
     * <pre>
     * interval mean
     * </pre>
     *
     * <code>double tps = 8;</code>
     */
    public Builder setTps(double value) {
      
      tps_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * interval mean
     * </pre>
     *
     * <code>double tps = 8;</code>
     */
    public Builder clearTps() {
      
      tps_ = 0D;
      onChanged();
      return this;
    }

    private double avgTime_ ;
    /**
     * <pre>
     * average calling millisecond
     * </pre>
     *
     * <code>double avgTime = 11;</code>
     */
    public double getAvgTime() {
      return avgTime_;
    }
    /**
     * <pre>
     * average calling millisecond
     * </pre>
     *
     * <code>double avgTime = 11;</code>
     */
    public Builder setAvgTime(double value) {
      
      avgTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * average calling millisecond
     * </pre>
     *
     * <code>double avgTime = 11;</code>
     */
    public Builder clearAvgTime() {
      
      avgTime_ = 0D;
      onChanged();
      return this;
    }

    private double succRate_ ;
    /**
     * <code>double succRate = 12;</code>
     */
    public double getSuccRate() {
      return succRate_;
    }
    /**
     * <code>double succRate = 12;</code>
     */
    public Builder setSuccRate(double value) {
      
      succRate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double succRate = 12;</code>
     */
    public Builder clearSuccRate() {
      
      succRate_ = 0D;
      onChanged();
      return this;
    }

    private long ct_ ;
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public long getCt() {
      return ct_;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public Builder setCt(long value) {
      
      ct_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * timestamp
     * </pre>
     *
     * <code>uint64 ct = 9;</code>
     */
    public Builder clearCt() {
      
      ct_ = 0L;
      onChanged();
      return this;
    }

    private long mt_ ;
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public long getMt() {
      return mt_;
    }
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public Builder setMt(long value) {
      
      mt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * modify timestamp
     * </pre>
     *
     * <code>uint64 mt = 10;</code>
     */
    public Builder clearMt() {
      
      mt_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ChannelTotalStat)
  }

  // @@protoc_insertion_point(class_scope:ChannelTotalStat)
  private static final dimit.store.ChannelTotalStat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dimit.store.ChannelTotalStat();
  }

  public static dimit.store.ChannelTotalStat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelTotalStat>
      PARSER = new com.google.protobuf.AbstractParser<ChannelTotalStat>() {
    public ChannelTotalStat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelTotalStat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelTotalStat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelTotalStat> getParserForType() {
    return PARSER;
  }

  public dimit.store.ChannelTotalStat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

