// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStore.proto

package dimit.store;

public interface ChannelTotalStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelTotalStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 v = 1;</code>
   */
  int getV();

  /**
   * <pre>
   * ChannelConf's id
   * </pre>
   *
   * <code>string cid = 2;</code>
   */
  java.lang.String getCid();
  /**
   * <pre>
   * ChannelConf's id
   * </pre>
   *
   * <code>string cid = 2;</code>
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <code>uint64 sendSuccCount = 3;</code>
   */
  long getSendSuccCount();

  /**
   * <code>uint64 sendFailCount = 4;</code>
   */
  long getSendFailCount();

  /**
   * <pre>
   *  millisecond
   * </pre>
   *
   * <code>uint64 sendSuccTime = 5;</code>
   */
  long getSendSuccTime();

  /**
   * <code>uint64 sendFailTime = 6;</code>
   */
  long getSendFailTime();

  /**
   * <code>uint64 recvSuccCount = 7;</code>
   */
  long getRecvSuccCount();

  /**
   * <code>uint64 recvFailCount = 8;</code>
   */
  long getRecvFailCount();

  /**
   * <pre>
   *total(ms = back - send)
   * </pre>
   *
   * <code>uint64 sendRecvTime = 12;</code>
   */
  long getSendRecvTime();

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  long getCt();

  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  long getMt();
}
