// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStore.proto

package dimit.store;

public interface ChannelRecvStatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ChannelRecvStat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 v = 1;</code>
   */
  int getV();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Channel's id
   * </pre>
   *
   * <code>string channel = 3;</code>
   */
  java.lang.String getChannel();
  /**
   * <pre>
   * Channel's id
   * </pre>
   *
   * <code>string channel = 3;</code>
   */
  com.google.protobuf.ByteString
      getChannelBytes();

  /**
   * <code>uint64 succCount = 4;</code>
   */
  long getSuccCount();

  /**
   * <code>uint64 failCount = 5;</code>
   */
  long getFailCount();

  /**
   * <code>double tps = 8;</code>
   */
  double getTps();

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  long getCt();

  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  long getMt();
}
