// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dimitStore.proto

package dimit.store;

public interface DimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dimit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 v = 1;</code>
   */
  int getV();

  /**
   * <pre>
   * instance id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * instance id
   * </pre>
   *
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * DimitConf id
   * </pre>
   *
   * <code>string cid = 3;</code>
   */
  java.lang.String getCid();
  /**
   * <pre>
   * DimitConf id
   * </pre>
   *
   * <code>string cid = 3;</code>
   */
  com.google.protobuf.ByteString
      getCidBytes();

  /**
   * <pre>
   * application name
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * application name
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * host name
   * </pre>
   *
   * <code>string host = 5;</code>
   */
  java.lang.String getHost();
  /**
   * <pre>
   * host name
   * </pre>
   *
   * <code>string host = 5;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>string ipv4 = 6;</code>
   */
  java.lang.String getIpv4();
  /**
   * <code>string ipv4 = 6;</code>
   */
  com.google.protobuf.ByteString
      getIpv4Bytes();

  /**
   * <code>string ipv6 = 7;</code>
   */
  java.lang.String getIpv6();
  /**
   * <code>string ipv6 = 7;</code>
   */
  com.google.protobuf.ByteString
      getIpv6Bytes();

  /**
   * <pre>
   *progress id
   * </pre>
   *
   * <code>string pid = 8;</code>
   */
  java.lang.String getPid();
  /**
   * <pre>
   *progress id
   * </pre>
   *
   * <code>string pid = 8;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <pre>
   *int32 port = 9; // progress port
   * </pre>
   *
   * <code>.Dimit.DimitStatus status = 12;</code>
   */
  int getStatusValue();
  /**
   * <pre>
   *int32 port = 9; // progress port
   * </pre>
   *
   * <code>.Dimit.DimitStatus status = 12;</code>
   */
  dimit.store.Dimit.DimitStatus getStatus();

  /**
   * <code>.Dimit.DimitRole role = 13;</code>
   */
  int getRoleValue();
  /**
   * <code>.Dimit.DimitRole role = 13;</code>
   */
  dimit.store.Dimit.DimitRole getRole();

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>uint64 ct = 9;</code>
   */
  long getCt();

  /**
   * <pre>
   * modify timestamp
   * </pre>
   *
   * <code>uint64 mt = 10;</code>
   */
  long getMt();
}
